In [1]:
!git clone https://github.com/hyperchancellor07/NLP-Dialogue-Summarization.git

Cloning into 'NLP-Dialogue-Summarization'...
remote: Enumerating objects: 86, done.
remote: Counting objects: 100% (86/86), done.
remote: Compressing objects: 100% (62/62), done.
remote: Total 86 (delta 30), reused 68 (delta 20), pack-reused 0 (from 0)
Receiving objects: 100% (86/86), 14.17 MiB | 9.87 MiB/s, done.
Resolving deltas: 100% (30/30), done.
Updating files: 100% (58/58), done.

In [2]:
%cd NLP-Dialogue-Summarization

/content/NLP-Dialogue-Summarization

In [3]:
!pip install -r requirements.txt

Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 2)) (6.0.3)
Requirement already satisfied: python-box in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 3)) (7.4.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 4)) (4.67.3)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 7)) (2.10.0+cu128)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 8)) (5.0.0)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 9)) (4.0.0)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 10)) (0.2.1)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 11)) (1.13.0)
Collecting rouge-score (from -r requirements.txt (line 14))
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Collecting evaluate (from -r requirements.txt (line 15))
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 18)) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 19)) (2.2.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 20)) (3.10.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 21)) (0.13.2)
Collecting streamlit (from -r requirements.txt (line 24))
  Downloading streamlit-1.57.0-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 27)) (1.6.1)
Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 33)) (1.11.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 7)) (3.29.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 7)) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 7)) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 7)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 7)) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 7)) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 7)) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 7)) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 7)) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 7)) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 7)) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 7)) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 7)) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 7)) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 7)) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 7)) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 7)) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 7)) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 7)) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 7)) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 7)) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 7)) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 7)) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 7)) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch->-r requirements.txt (line 7)) (1.5.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers->-r requirements.txt (line 8)) (26.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers->-r requirements.txt (line 8)) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers->-r requirements.txt (line 8)) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers->-r requirements.txt (line 8)) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers->-r requirements.txt (line 8)) (0.7.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets->-r requirements.txt (line 9)) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets->-r requirements.txt (line 9)) (0.3.8)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets->-r requirements.txt (line 9)) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets->-r requirements.txt (line 9)) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets->-r requirements.txt (line 9)) (0.70.16)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate->-r requirements.txt (line 11)) (5.9.5)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from rouge-score->-r requirements.txt (line 14)) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from rouge-score->-r requirements.txt (line 14)) (3.9.1)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from rouge-score->-r requirements.txt (line 14)) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->-r requirements.txt (line 19)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->-r requirements.txt (line 19)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->-r requirements.txt (line 19)) (2026.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 20)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 20)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 20)) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 20)) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 20)) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 20)) (3.3.2)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r requirements.txt (line 24)) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r requirements.txt (line 24)) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r requirements.txt (line 24)) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r requirements.txt (line 24)) (8.3.3)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r requirements.txt (line 24)) (3.1.47)
Collecting pydeck<1,>=0.8.0b4 (from streamlit->-r requirements.txt (line 24))
  Downloading pydeck-0.9.2-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: protobuf<8,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r requirements.txt (line 24)) (5.29.6)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r requirements.txt (line 24)) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r requirements.txt (line 24)) (0.10.2)
Requirement already satisfied: starlette>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r requirements.txt (line 24)) (0.52.1)
Requirement already satisfied: uvicorn>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r requirements.txt (line 24)) (0.46.0)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r requirements.txt (line 24)) (0.7.1)
Requirement already satisfied: anyio>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r requirements.txt (line 24)) (4.13.0)
Requirement already satisfied: python-multipart>=0.0.10 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r requirements.txt (line 24)) (0.0.26)
Requirement already satisfied: websockets>=12.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r requirements.txt (line 24)) (15.0.1)
Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r requirements.txt (line 24)) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r requirements.txt (line 24)) (6.0.0)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->-r requirements.txt (line 27)) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->-r requirements.txt (line 27)) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->-r requirements.txt (line 27)) (3.6.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->-r requirements.txt (line 33)) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->-r requirements.txt (line 33)) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->-r requirements.txt (line 33)) (0.24.2)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit->-r requirements.txt (line 24)) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit->-r requirements.txt (line 24)) (2.20.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio>=4.0.0->streamlit->-r requirements.txt (line 24)) (3.13)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets->-r requirements.txt (line 9)) (3.13.5)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit->-r requirements.txt (line 24)) (4.0.12)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->-r requirements.txt (line 33)) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->-r requirements.txt (line 33)) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub->-r requirements.txt (line 33)) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch->-r requirements.txt (line 7)) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets->-r requirements.txt (line 9)) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets->-r requirements.txt (line 9)) (2.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch->-r requirements.txt (line 7)) (1.3.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub->-r requirements.txt (line 33)) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub->-r requirements.txt (line 33)) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub->-r requirements.txt (line 33)) (0.0.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->-r requirements.txt (line 9)) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->-r requirements.txt (line 9)) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->-r requirements.txt (line 9)) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->-r requirements.txt (line 9)) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->-r requirements.txt (line 9)) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->-r requirements.txt (line 9)) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->-r requirements.txt (line 9)) (1.23.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit->-r requirements.txt (line 24)) (5.0.3)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit->-r requirements.txt (line 24)) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit->-r requirements.txt (line 24)) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit->-r requirements.txt (line 24)) (0.30.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub->-r requirements.txt (line 33)) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub->-r requirements.txt (line 33)) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface_hub->-r requirements.txt (line 33)) (0.1.2)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 5.0 MB/s eta 0:00:00
Downloading streamlit-1.57.0-py3-none-any.whl (9.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 107.8 MB/s eta 0:00:00
Downloading pydeck-0.9.2-py2.py3-none-any.whl (11.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 125.0 MB/s eta 0:00:00
Building wheels for collected packages: rouge-score
  Building wheel for rouge-score (setup.py) ... done
  Created wheel for rouge-score: filename=rouge_score-0.1.2-py3-none-any.whl size=24934 sha256=fbbac97d6b0ecd6779e2463c7d677a4b69d35f802fd3e7cbf4c6ca02469a680b
  Stored in directory: /root/.cache/pip/wheels/85/9d/af/01feefbe7d55ef5468796f0c68225b6788e85d9d0a281e7a70
Successfully built rouge-score
Installing collected packages: rouge-score, pydeck, streamlit, evaluate
Successfully installed evaluate-0.4.6 pydeck-0.9.2 rouge-score-0.1.2 streamlit-1.57.0

In [4]:
!pip install -q transformers peft accelerate sentencepiece rouge_score datasets pandas

In [5]:
import torch
import pandas as pd
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSeq2SeqLM,
)
from peft import (
    PeftModel,
)

In [6]:
device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)
print("Using device:", device)

Using device: cuda

In [7]:
dataset = load_dataset("knkarthick/samsum")
test_dataset = dataset["test"]
print(test_dataset[0])

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

train.csv: 0.00B [00:00, ?B/s]

validation.csv: 0.00B [00:00, ?B/s]

test.csv: 0.00B [00:00, ?B/s]

Generating train split:   0%|          | 0/14731 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/818 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/819 [00:00<?, ? examples/s]

{'id': '13862856', 'dialogue': "Hannah: Hey, do you have Betty's number?\nAmanda: Lemme check\nHannah: <file_gif>\nAmanda: Sorry, can't find it.\nAmanda: Ask Larry\nAmanda: He called her last time we were at the park together\nHannah: I don't know him well\nHannah: <file_gif>\nAmanda: Don't be shy, he's very nice\nHannah: If you say so..\nHannah: I'd rather you texted him\nAmanda: Just text him 🙂\nHannah: Urgh.. Alright\nHannah: Bye\nAmanda: Bye bye", 'summary': "Hannah needs Betty's number but Amanda doesn't have it. She needs to contact Larry."}

In [8]:
BASELINE_MODEL = "google/pegasus-large"
baseline_tokenizer = AutoTokenizer.from_pretrained(
    BASELINE_MODEL
)
baseline_model = AutoModelForSeq2SeqLM.from_pretrained(
    BASELINE_MODEL
)
baseline_model.to(device)

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json:   0%|          | 0.00/88.0 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/1.91M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/65.0 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/2.28G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/680 [00:00<?, ?it/s]

Error during conversion: ReadTimeout('The read operation timed out')

model.safetensors:   0%|          | 0.00/2.28G [00:00<?, ?B/s]

The tied weights mapping and config for this model specifies to tie model.shared.weight to model.decoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie model.shared.weight to model.encoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
PegasusForConditionalGeneration LOAD REPORT from: google/pegasus-large
Key                                  | Status  |
-------------------------------------+---------+-
model.decoder.embed_positions.weight | MISSING |
model.encoder.embed_positions.weight | MISSING |

Notes:
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

generation_config.json:   0%|          | 0.00/260 [00:00<?, ?B/s]

PegasusForConditionalGeneration(
  (model): PegasusModel(
    (shared): Embedding(96103, 1024, padding_idx=0)
    (encoder): PegasusEncoder(
      (embed_tokens): Embedding(96103, 1024, padding_idx=0)
      (embed_positions): PegasusSinusoidalPositionalEmbedding(1024, 1024)
      (layers): ModuleList(
        (0-15): 16 x PegasusEncoderLayer(
          (self_attn): PegasusAttention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (activation_fn): ReLU()
          (fc1): Linear(in_features=1024, out_features=4096, bias=True)
          (fc2): Linear(in_features=4096, out_features=1024, bias=True)
          (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        )
      )
      (layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
    )
    (decoder): PegasusDecoder(
      (embed_tokens): Embedding(96103, 1024, padding_idx=0)
      (embed_positions): PegasusSinusoidalPositionalEmbedding(1024, 1024)
      (layers): ModuleList(
        (0-15): 16 x PegasusDecoderLayer(
          (self_attn): PegasusAttention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (activation_fn): ReLU()
          (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (encoder_attn): PegasusAttention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (encoder_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (fc1): Linear(in_features=1024, out_features=4096, bias=True)
          (fc2): Linear(in_features=4096, out_features=1024, bias=True)
          (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        )
      )
      (layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
    )
  )
  (lm_head): Linear(in_features=1024, out_features=96103, bias=False)
)

In [9]:
FULL_FT_MODEL = "hyperchancellor07/pegasus-samsum-dialogue-summarizer"
full_ft_tokenizer = AutoTokenizer.from_pretrained(
    FULL_FT_MODEL
)
full_ft_model = AutoModelForSeq2SeqLM.from_pretrained(
    FULL_FT_MODEL
)
full_ft_model.to(device)

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

spiece.model:   0%|          | 0.00/1.91M [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/2.28G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/680 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/255 [00:00<?, ?B/s]

PegasusForConditionalGeneration(
  (model): PegasusModel(
    (shared): Embedding(96103, 1024, padding_idx=0)
    (encoder): PegasusEncoder(
      (embed_tokens): Embedding(96103, 1024, padding_idx=0)
      (embed_positions): PegasusSinusoidalPositionalEmbedding(1024, 1024)
      (layers): ModuleList(
        (0-15): 16 x PegasusEncoderLayer(
          (self_attn): PegasusAttention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (activation_fn): ReLU()
          (fc1): Linear(in_features=1024, out_features=4096, bias=True)
          (fc2): Linear(in_features=4096, out_features=1024, bias=True)
          (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        )
      )
      (layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
    )
    (decoder): PegasusDecoder(
      (embed_tokens): Embedding(96103, 1024, padding_idx=0)
      (embed_positions): PegasusSinusoidalPositionalEmbedding(1024, 1024)
      (layers): ModuleList(
        (0-15): 16 x PegasusDecoderLayer(
          (self_attn): PegasusAttention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (activation_fn): ReLU()
          (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (encoder_attn): PegasusAttention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (encoder_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (fc1): Linear(in_features=1024, out_features=4096, bias=True)
          (fc2): Linear(in_features=4096, out_features=1024, bias=True)
          (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        )
      )
      (layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
    )
  )
  (lm_head): Linear(in_features=1024, out_features=96103, bias=False)
)

In [11]:
!pip uninstall torchao

Found existing installation: torchao 0.10.0
Uninstalling torchao-0.10.0:
  Would remove:
    /usr/local/lib/python3.12/dist-packages/torchao-0.10.0.dist-info/*
    /usr/local/lib/python3.12/dist-packages/torchao/*
Proceed (Y/n)? y
  Successfully uninstalled torchao-0.10.0

In [12]:
LORA_MODEL = "hyperchancellor07/pegasus_lora"
lora_tokenizer = AutoTokenizer.from_pretrained(
    BASELINE_MODEL
)
base_lora_model = AutoModelForSeq2SeqLM.from_pretrained(
    BASELINE_MODEL
)
lora_model = PeftModel.from_pretrained(
    base_lora_model,
    LORA_MODEL,
)
lora_model.to(device)

Loading weights:   0%|          | 0/680 [00:00<?, ?it/s]

Error during conversion: ReadTimeout('The read operation timed out')
The tied weights mapping and config for this model specifies to tie model.shared.weight to model.decoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie model.shared.weight to model.encoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
PegasusForConditionalGeneration LOAD REPORT from: google/pegasus-large
Key                                  | Status  |
-------------------------------------+---------+-
model.decoder.embed_positions.weight | MISSING |
model.encoder.embed_positions.weight | MISSING |

Notes:
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

adapter_model.safetensors:   0%|          | 0.00/12.6M [00:00<?, ?B/s]

PeftModelForSeq2SeqLM(
  (base_model): LoraModel(
    (model): PegasusForConditionalGeneration(
      (model): PegasusModel(
        (shared): Embedding(96103, 1024, padding_idx=0)
        (encoder): PegasusEncoder(
          (embed_tokens): Embedding(96103, 1024, padding_idx=0)
          (embed_positions): PegasusSinusoidalPositionalEmbedding(1024, 1024)
          (layers): ModuleList(
            (0-15): 16 x PegasusEncoderLayer(
              (self_attn): PegasusAttention(
                (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
                (v_proj): lora.Linear(
                  (base_layer): Linear(in_features=1024, out_features=1024, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.1, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=1024, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=1024, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (q_proj): lora.Linear(
                  (base_layer): Linear(in_features=1024, out_features=1024, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.1, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=1024, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=1024, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
              )
              (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
              (activation_fn): ReLU()
              (fc1): Linear(in_features=1024, out_features=4096, bias=True)
              (fc2): Linear(in_features=4096, out_features=1024, bias=True)
              (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            )
          )
          (layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        )
        (decoder): PegasusDecoder(
          (embed_tokens): Embedding(96103, 1024, padding_idx=0)
          (embed_positions): PegasusSinusoidalPositionalEmbedding(1024, 1024)
          (layers): ModuleList(
            (0-15): 16 x PegasusDecoderLayer(
              (self_attn): PegasusAttention(
                (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
                (v_proj): lora.Linear(
                  (base_layer): Linear(in_features=1024, out_features=1024, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.1, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=1024, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=1024, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (q_proj): lora.Linear(
                  (base_layer): Linear(in_features=1024, out_features=1024, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.1, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=1024, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=1024, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
              )
              (activation_fn): ReLU()
              (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
              (encoder_attn): PegasusAttention(
                (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
                (v_proj): lora.Linear(
                  (base_layer): Linear(in_features=1024, out_features=1024, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.1, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=1024, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=1024, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (q_proj): lora.Linear(
                  (base_layer): Linear(in_features=1024, out_features=1024, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.1, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=1024, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=1024, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
              )
              (encoder_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
              (fc1): Linear(in_features=1024, out_features=4096, bias=True)
              (fc2): Linear(in_features=4096, out_features=1024, bias=True)
              (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            )
          )
          (layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        )
      )
      (lm_head): Linear(in_features=1024, out_features=96103, bias=False)
    )
  )
)

In [13]:
def generate_summary(
    model,
    tokenizer,
    dialogue_text,
):
    dialogue_text = "summarize: " + dialogue_text
    inputs = tokenizer(
        dialogue_text,
        return_tensors="pt",
        truncation=True,
        padding="max_length",
        max_length=512,
    )
    inputs = {
        key: value.to(device)
        for key, value in inputs.items()
    }
    summary_ids = model.generate(
        **inputs,
        max_length=96,
        min_length=8,
        num_beams=8,
        repetition_penalty=2.5,
        no_repeat_ngram_size=3,
        length_penalty=1.0,
        early_stopping=True,
    )
    generated_summary = tokenizer.decode(
        summary_ids[0],
        skip_special_tokens=True,
    )
    return generated_summary

In [14]:
sample = test_dataset[10]
dialogue = sample["dialogue"]
reference_summary = sample["summary"]
baseline_summary = generate_summary(
    baseline_model,
    baseline_tokenizer,
    dialogue,
)
full_ft_summary = generate_summary(
    full_ft_model,
    full_ft_tokenizer,
    dialogue,
)
lora_summary = generate_summary(
    lora_model,
    lora_tokenizer,
    dialogue,
)
print("=" * 80)
print("DIALOGUE")
print("=" * 80)
print(dialogue)
print("\nREFERENCE SUMMARY:\n")
print(reference_summary)
print("\nBASELINE PEGASUS SUMMARY:\n")
print(baseline_summary)
print("\nFULL FINETUNED SUMMARY:\n")
print(full_ft_summary)
print("\nLORA FINETUNED SUMMARY:\n")
print(lora_summary)

================================================================================
DIALOGUE
================================================================================
Wanda: Let's make a party!
Gina: Why?
Wanda: beacuse. I want some fun!
Gina: ok, what do u need?
Wanda: 1st I need too make a list
Gina: noted and then?
Wanda: well, could u take yours father car and go do groceries with me?
Gina: don't know if he'll agree
Wanda: I know, but u can ask :)
Gina: I'll try but theres no promisess
Wanda: I know, u r the best!
Gina: When u wanna go
Wanda: Friday?
Gina: ok, I'll ask

REFERENCE SUMMARY:

Wanda wants to throw a party. She asks Gina to borrow her father's car and go do groceries together. They set the date for Friday.

BASELINE PEGASUS SUMMARY:

me Woburn institutions first – paid company Higuain part no process her 400 her need called know oncere usinging way); may want journey many simply may teacher know | well

FULL FINETUNED SUMMARY:

Gina will take Wanda's father car and go do groceries with her.

LORA FINETUNED SUMMARY:

Gina relaxation. know provided her It

In [15]:
comparison_df = pd.DataFrame({
    "Model": [
        "Baseline PEGASUS",
        "Full Fine-Tuned PEGASUS",
        "LoRA PEGASUS",
    ],

    "Generated Summary": [
        baseline_summary,
        full_ft_summary,
        lora_summary,
    ]
})
comparison_df

                     Model                                  Generated Summary
0         Baseline PEGASUS  me Woburn institutions first – paid company Hi...
1  Full Fine-Tuned PEGASUS  Gina will take Wanda's father car and go do gr...
2             LoRA PEGASUS              Gina relaxation. know provided her It

In [16]:
real_world_dialogues = [

    """
    Sam: yoo u coming tmrw?
    Jay: maybe bro depends on attendance 💀
    Sam: teacher mad af today
    Jay: ikr 😭
    Sam: bring charger btw
    Jay: kk
    """,


    """
    Mike: training crashed again
    Alex: CUDA out of memory?
    Mike: yeah batch size too high
    Alex: switch to gradient accumulation
    Mike: trying LoRA now
    """,


    """
    Customer: my account stopped working
    Agent: suspicious login detected
    Customer: can u unlock it pls
    Agent: reset password after login
    """
]

In [17]:
for i, dialogue in enumerate(real_world_dialogues):

    print("\n" + "=" * 100)
    print(f"REAL-WORLD DRIFT SAMPLE {i+1}")
    print("=" * 100)
    print("\nDIALOGUE:\n")
    print(dialogue)
    baseline_summary = generate_summary(
        baseline_model,
        baseline_tokenizer,
        dialogue,
    )
    full_ft_summary = generate_summary(
        full_ft_model,
        full_ft_tokenizer,
        dialogue,
    )
    lora_summary = generate_summary(
        lora_model,
        lora_tokenizer,
        dialogue,
    )
    print("\nBASELINE SUMMARY:\n")
    print(baseline_summary)
    print("\nFULL FT SUMMARY:\n")
    print(full_ft_summary)
    print("\nLORA SUMMARY:\n")
    print(lora_summary)

====================================================================================================
REAL-WORLD DRIFT SAMPLE 1
====================================================================================================

DIALOGUE:


    Sam: yoo u coming tmrw?
    Jay: maybe bro depends on attendance 💀
    Sam: teacher mad af today
    Jay: ikr 😭
    Sam: bring charger btw
    Jay: kk


BASELINE SUMMARY:

Jay good these too through college through smiles through immigrants first 4 through UM should urgeve us Money through Course asset should stipulated completeve staffrun making no him week” – quickly Jayor well only mem ' day variety source Choir concern hours reasons fence well

FULL FT SUMMARY:

Jay is coming to Sam's class today.

LORA SUMMARY:

Sam It CSUo. join of

====================================================================================================
REAL-WORLD DRIFT SAMPLE 2
====================================================================================================

DIALOGUE:


    Mike: training crashed again
    Alex: CUDA out of memory?
    Mike: yeah batch size too high
    Alex: switch to gradient accumulation
    Mike: trying LoRA now


BASELINE SUMMARY:

mem flesh should Serviceve day Aug Children however through informed now socks leverage now socks 44 now socks

FULL FT SUMMARY:

Mike's training crashed again. Alex is trying LoRA now.

LORA SUMMARY:

Mike is size. too of her new

====================================================================================================
REAL-WORLD DRIFT SAMPLE 3
====================================================================================================

DIALOGUE:


    Customer: my account stopped working
    Agent: suspicious login detected
    Customer: can u unlock it pls
    Agent: reset password after login


BASELINE SUMMARY:

mevolt malfunctions first mounting should Deathveit adds cost need usuallyA while reporting help exhibit may – |re need impacts global through Board songsing said pregnant after need minutes - did[ things home University well captter nurses role purchased sensitive cap Tur

FULL FT SUMMARY:

summarize: Customer's account stopped working Agent suspicious login detected Customer can unlock it pls Agent reset password after login.

LORA SUMMARY:

Customer account stopped login her flow.

In [18]:
print("=" * 80)
print("RESEARCH OBSERVATIONS")
print("=" * 80)

================================================================================
RESEARCH OBSERVATIONS
================================================================================

In [19]:
print(
    """
1. Baseline PEGASUS behavior:
- General summarization capability
- Weak conversational adaptation
- Possible hallucinations or repetition


2. Full Fine-Tuned PEGASUS behavior:
- Strong conversational understanding
- Better dialogue compression
- Improved robustness on SAMSum-like data


3. LoRA Fine-Tuned behavior:
- Parameter-efficient adaptation
- Reduced compute requirement
- Performance tradeoff vs full fine-tuning


4. Drift Analysis:
- Informal slang introduces distribution shift
- Emoji-heavy dialogue challenges semantic compression
- Technical jargon affects summarization consistency


5. Overall Research Insight:
- Transfer learning enables conversational adaptation
- Fine-tuning improves robustness under conversational drift
- PEFT methods provide efficient transformer adaptation
"""
)

1. Baseline PEGASUS behavior:
- General summarization capability
- Weak conversational adaptation
- Possible hallucinations or repetition


2. Full Fine-Tuned PEGASUS behavior:
- Strong conversational understanding
- Better dialogue compression
- Improved robustness on SAMSum-like data


3. LoRA Fine-Tuned behavior:
- Parameter-efficient adaptation
- Reduced compute requirement
- Performance tradeoff vs full fine-tuning


4. Drift Analysis:
- Informal slang introduces distribution shift
- Emoji-heavy dialogue challenges semantic compression
- Technical jargon affects summarization consistency


5. Overall Research Insight:
- Transfer learning enables conversational adaptation
- Fine-tuning improves robustness under conversational drift
- PEFT methods provide efficient transformer adaptation

In [21]:
!pip install -q evaluate rouge_score

In [22]:
import evaluate
rouge_metric = evaluate.load("rouge")

Downloading builder script: 0.00B [00:00, ?B/s]

In [24]:
evaluation_samples = 50
baseline_predictions = []
full_ft_predictions = []
lora_predictions = []
reference_summaries = []

In [25]:
for i in range(evaluation_samples):
    sample = test_dataset[i]
    dialogue = sample["dialogue"]
    reference_summary = sample["summary"]
    baseline_summary = generate_summary(
        baseline_model,
        baseline_tokenizer,
        dialogue,
    )
    # FULL FT
    full_ft_summary = generate_summary(
        full_ft_model,
        full_ft_tokenizer,
        dialogue,
    )
    # LORA
    lora_summary = generate_summary(
        lora_model,
        lora_tokenizer,
        dialogue,
    )
    baseline_predictions.append(
        baseline_summary
    )
    full_ft_predictions.append(
        full_ft_summary
    )
    lora_predictions.append(
        lora_summary
    )
    reference_summaries.append(
        reference_summary
    )

In [27]:
baseline_rouge = rouge_metric.compute(
    predictions=baseline_predictions,
    references=reference_summaries,
)
full_ft_rouge = rouge_metric.compute(
    predictions=full_ft_predictions,
    references=reference_summaries,
)
lora_rouge = rouge_metric.compute(
    predictions=lora_predictions,
    references=reference_summaries,
)

In [28]:
results_df = pd.DataFrame({

    "Model": [
        "Baseline PEGASUS",
        "Full Fine-Tuned PEGASUS",
        "LoRA PEGASUS",
    ],

    "ROUGE-1": [
        baseline_rouge["rouge1"],
        full_ft_rouge["rouge1"],
        lora_rouge["rouge1"],
    ],

    "ROUGE-2": [
        baseline_rouge["rouge2"],
        full_ft_rouge["rouge2"],
        lora_rouge["rouge2"],
    ],

    "ROUGE-L": [
        baseline_rouge["rougeL"],
        full_ft_rouge["rougeL"],
        lora_rouge["rougeL"],
    ],
})

In [29]:
results_df

                     Model   ROUGE-1   ROUGE-2   ROUGE-L
0         Baseline PEGASUS  0.013508  0.000000  0.012841
1  Full Fine-Tuned PEGASUS  0.433800  0.198466  0.359550
2             LoRA PEGASUS  0.166906  0.000000  0.135296

In [31]:
from pathlib import Path
RESULTS_DIR = Path(
    "/content/NLP-Dialogue-Summarization/artifacts/results"
)

RESULTS_DIR.mkdir(
    parents=True,
    exist_ok=True,
)
results_df.to_csv(

    RESULTS_DIR / "rouge_results.csv",

    index=False,
)
print(
    "ROUGE results saved successfully."
)

ROUGE results saved successfully.

HYBRID drift robustness Score(HDRS)

In [32]:
!pip install -q sentence-transformers rank_bm25 scikit-learn

In [33]:
import numpy as np
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from rank_bm25 import BM25Okapi

In [34]:
embedding_model = SentenceTransformer(
    "all-MiniLM-L6-v2"
)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [36]:
def semantic_similarity(
    reference,
    generated,
):
    reference_embedding = embedding_model.encode(
        [reference]
    )
    generated_embedding = embedding_model.encode(
        [generated]
    )
    similarity = cosine_similarity(
        reference_embedding,
        generated_embedding,
    )[0][0]
    return float(similarity)

In [37]:
def sparse_similarity(
    reference,
    generated,
):
    corpus = [reference.split()]
    bm25 = BM25Okapi(corpus)
    tokenized_generated = generated.split()
    score = bm25.get_scores(
        tokenized_generated
    )[0]
    normalized_score = score / 10
    return min(
        float(normalized_score),
        1.0,
    )

In [38]:
def compute_hdrs(
    reference_summary,
    generated_summary,
):
    semantic_score = semantic_similarity(
        reference_summary,
        generated_summary,
    )
    sparse_score = sparse_similarity(
        reference_summary,
        generated_summary,
    )
    hdrs = (
        0.7 * semantic_score
        +
        0.3 * sparse_score
    )
    return {
        "semantic_similarity": round(
            semantic_score,
            4,
        ),
        "sparse_similarity": round(
            sparse_score,
            4,
        ),
        "HDRS": round(
            hdrs,
            4,
        ),
    }

In [39]:
sample = test_dataset[15]
dialogue = sample["dialogue"]
reference_summary = sample["summary"]

In [40]:

baseline_summary = generate_summary(
    baseline_model,
    baseline_tokenizer,
    dialogue,
)
full_ft_summary = generate_summary(
    full_ft_model,
    full_ft_tokenizer,
    dialogue,
)
lora_summary = generate_summary(
    lora_model,
    lora_tokenizer,
    dialogue,
)

In [43]:
baseline_hdrs = compute_hdrs(
    reference_summary,
    baseline_summary,
)
full_ft_hdrs = compute_hdrs(
    reference_summary,
    full_ft_summary,
)
lora_hdrs = compute_hdrs(
    reference_summary,
    lora_summary,
)

In [46]:

hdrs_df = pd.DataFrame({
    "Model": [
        "Baseline PEGASUS",
        "Full Fine-Tuned PEGASUS",
        "LoRA PEGASUS",
    ],
    "Semantic Similarity": [
        baseline_hdrs["semantic_similarity"],
        full_ft_hdrs["semantic_similarity"],
        lora_hdrs["semantic_similarity"],
    ],
    "Sparse Similarity": [
        baseline_hdrs["sparse_similarity"],
        full_ft_hdrs["sparse_similarity"],
        lora_hdrs["sparse_similarity"],
    ],

    "HDRS": [
        baseline_hdrs["HDRS"],
        full_ft_hdrs["HDRS"],
        lora_hdrs["HDRS"],
    ]
})

In [47]:
hdrs_df

                     Model  Semantic Similarity  Sparse Similarity    HDRS
0         Baseline PEGASUS               0.1657             0.0000  0.1160
1  Full Fine-Tuned PEGASUS               0.7574            -0.1609  0.4819
2             LoRA PEGASUS               0.3418            -0.0275  0.2310

In [48]:
hdrs_df.to_csv(
    RESULTS_DIR / "hdrs_results.csv",
    index=False,
)

In [49]:
%cd /content/NLP-Dialogue-Summarization

/content/NLP-Dialogue-Summarization

In [52]:
!find / -name "*.ipynb" 2>/dev/null

/usr/local/lib/python3.12/dist-packages/nbclassic/bundler/tests/resources/empty.ipynb
/usr/local/lib/python3.12/dist-packages/notebook/bundler/tests/resources/empty.ipynb
/usr/local/lib/python3.12/dist-packages/panel/tests/ui/io/app.ipynb
/usr/local/lib/python3.12/dist-packages/wasabi/tests/test-data/wasabi-test-notebook.ipynb
/usr/local/lib/python3.12/dist-packages/spreg/optional_imports.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/tests/ipython/notebooks/test_opts_image_cell_magic_offset.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/tests/ipython/notebooks/test_output_svg_line_magic.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/tests/ipython/notebooks/test_opts_image_line_magic.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/tests/ipython/notebooks/test_opts_image_cell_magic.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/plotly/trisurf3d_demo.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/plotly/surface_3d.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/mandelbrot_section.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/autompg_violins.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/dropdown_economic.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/iris_density_grid.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/route_chord.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/bars_economic.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/histogram_example.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/box_draw_roi_editor.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/point_draw_triangulate.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/energy_sankey.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/html_hover_tooltips.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/square_limit.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/iris_grouped_grid.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/quiver_demo.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/nyc_airport_connections.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/iris_splom_example.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/texas_choropleth_example.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/life_expectancy_split_violin.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/hextile_movie_ratings.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/multichannel_timeseries_viewer.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/topographic_hillshading.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/timeseries_range_tool.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/autompg_histogram.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/step_chart.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/scatter_economic.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/network_graph.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/us_unemployment.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/nyc_radial_heatmap.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/lorenz_attractor_example.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/dot_example.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/legend_example.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/iris_example.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/irregular_quadmesh.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/choropleth_data_link.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/measles_example.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/verhulst_mandelbrot.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/area_chart.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/dragon_curve.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/lesmis_example.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/bachelors_degrees_by_gender.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/directed_airline_routes.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/emoji_tsne.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/stocks_example.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/boxplot_chart.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/bokeh/image_range_tool.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/matplotlib/mandelbrot_section.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/matplotlib/autompg_violins.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/matplotlib/trisurf3d_demo.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/matplotlib/dropdown_economic.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/matplotlib/iris_density_grid.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/matplotlib/polar_scatter_demo.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/matplotlib/route_chord.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/matplotlib/bars_economic.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/matplotlib/histogram_example.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/matplotlib/energy_sankey.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/matplotlib/square_limit.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/matplotlib/iris_grouped_grid.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/matplotlib/surface_3d.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/matplotlib/quiver_demo.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/matplotlib/nyc_airport_connections.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/matplotlib/iris_splom_example.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/matplotlib/texas_choropleth_example.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/matplotlib/hextile_movie_ratings.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/matplotlib/topographic_hillshading.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/matplotlib/autompg_histogram.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/matplotlib/step_chart.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/matplotlib/scatter_economic.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/matplotlib/network_graph.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/matplotlib/us_unemployment.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/matplotlib/nyc_radial_heatmap.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/matplotlib/lorenz_attractor_example.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/matplotlib/legend_example.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/matplotlib/iris_example.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/matplotlib/irregular_quadmesh.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/matplotlib/measles_example.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/matplotlib/verhulst_mandelbrot.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/matplotlib/area_chart.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/matplotlib/dragon_curve.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/matplotlib/bachelors_degrees_by_gender.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/matplotlib/directed_airline_routes.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/matplotlib/stocks_example.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/gallery/demos/matplotlib/boxplot_chart.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/getting_started/3-Tabular_Datasets.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/getting_started/1-Introduction.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/getting_started/4-Gridded_Datasets.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/getting_started/2-Customization.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/getting_started/5-Live_Data.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/user_guide/17-Dashboards.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/user_guide/03-Applying_Customizations.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/user_guide/Annotators.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/user_guide/04-Style_Mapping.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/user_guide/Linked_Brushing.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/user_guide/13-Custom_Interactivity.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/user_guide/02-Composing_Elements.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/user_guide/Exporting_and_Archiving.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/user_guide/07-Live_Data.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/user_guide/12-Responding_to_Events.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/user_guide/Interactive_Hover_for_Big_Data.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/user_guide/09-Gridded_Datasets.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/user_guide/11-Transforming_Elements.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/user_guide/Plots_and_Renderers.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/user_guide/16-Streaming_Data.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/user_guide/Plotting_with_Bokeh.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/user_guide/Colormaps.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/user_guide/Notebook_Magics.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/user_guide/01-Annotating_Data.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/user_guide/Plotting_with_Matplotlib.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/user_guide/06-Building_Composite_Objects.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/user_guide/05-Dimensioned_Containers.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/user_guide/15-Large_Data.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/user_guide/Continuous_Coordinates.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/user_guide/Network_Graphs.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/user_guide/Customizing_Plots.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/user_guide/Deploying_Bokeh_Apps.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/user_guide/08-Tabular_Datasets.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/user_guide/14-Data_Pipelines.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/user_guide/10-Indexing_and_Selecting_Data.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/user_guide/Geometry_Data.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/user_guide/Linking_Plots.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/plotly/TriSurface.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/plotly/Area.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/plotly/RGB.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/plotly/Curve.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/plotly/Bounds.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/plotly/Box.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/plotly/Scatter3D.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/plotly/Histogram.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/plotly/ImageStack.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/plotly/Table.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/plotly/Violin.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/plotly/HLine.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/plotly/ErrorBars.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/plotly/Ellipse.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/plotly/BoxWhisker.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/plotly/Spread.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/plotly/HeatMap.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/plotly/Tiles.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/plotly/Points.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/plotly/HSpan.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/plotly/Scatter.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/plotly/Surface.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/plotly/Image.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/plotly/Bars.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/plotly/ItemTable.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/plotly/VLine.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/plotly/VSpan.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/plotly/Raster.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/plotly/Path3D.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/plotly/Distribution.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/Arrow.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/Area.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/RGB.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/HSpans.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/Chord.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/Curve.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/Polygons.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/HexTiles.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/Bounds.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/Box.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/Segments.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/TriMesh.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/Histogram.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/ImageStack.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/Slope.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/VSpans.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/Labels.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/VLines.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/Table.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/Sankey.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/Violin.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/HSV.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/Spikes.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/HLine.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/HLines.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/Graph.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/ErrorBars.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/Text.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/Ellipse.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/BoxWhisker.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/Contours.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/Path.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/Rectangles.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/Bivariate.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/Spread.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/HeatMap.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/Tiles.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/Points.ipynb
/usr/local/lib/python3.12/dist-packages/holoviews/examples/reference/elements/bokeh/HSpan.ipynb

In [59]:
!find / -name "07_comparative_drift_analysis.ipynb" 2>/dev/null

In [60]:
!cp "/content/drive/MyDrive/Colab Notebooks/07_comparative_drift_analysis.ipynb" "/content/NLP-Dialogue-Summarization/notebooks/"

cp: cannot stat '/content/drive/MyDrive/Colab Notebooks/07_comparative_drift_analysis.ipynb': No such file or directory